server:
  port: 8091
  ssl:
    key-store: file:/app/damoportal.p12
    key-store-password: damo123
    key-store-type: PKCS12
    enabled: true

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: portal_route
          uri: http://product-api:8080
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal/(?<remaining>.*), /${remaining}  # Remove '/portal' from the path
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 # per second
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1 # num tokens required per request
                key-resolver: "#{@productKeyResolver}"
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/customer-fallback
            - AddResponseHeader=foo, bar
        - id: bin
          uri: http://httpbin.org:80
          predicates:
            - Path=/get

  redis:
    host: redis
    port: 6379
