services:

  gateway-api:
    image: gateway-api:0.0.1-SNAPSHOT
    ports:
      - "6867:8091"
    volumes:
      - ./CA/out/damoportal.p12:/app/damoportal.p12
    networks:
      - damo_network

networks:
  damo_network:
    external: true