version: '3.8'
services:

  gateway-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "6867:8091"
    volumes:
      - ./CA/out/damoportal.p12:/app/damoportal.p12
    networks:
      - damo_network

networks:
  damo_network:
    external: true